#config file
name = "sayvai_tools"
version = "0.0.2"
description = "A collection of tools for the Sayvai agents"
author = "Sayvai"
url = "https://sayvai.io"

#setup
setup(
    name=name,
    version=version,
    description=description,
    author=author,
    url=url,
    packages=find_packages(),
    install_requires=[
        'langchain',
        'langchain_experimental',
        'google-api-python-client',
        'openai',
        'SQLAlchemy'
    ],
    include_package_data=True,
    zip_safe=False
)

#build
os.system('python setup.py sdist bdist_wheel')

#remove build
shutil.rmtree('build')